/* Generated by Kconfiglib */
#ifndef HV_KCONFIG
#define HV_KCONFIG

/**
 * @addtogroup hwmgmt_configs
 *
 * @{
 */

/**
 * @file
 * @brief {TBD brief description}
 *
 * {TBD detailed description, including purposes, designed usages, usage remarks and dependency justification}
 */
#define CONFIG_LOGICAL_PARTITION         1
#define CONFIG_SCHED_NOOP                1
#define CONFIG_BOARD                     "nuc7i7dnb"
#define CONFIG_RELEASE                   1
#define CONFIG_MAX_EMULATED_MMIO_REGIONS 16U
#define CONFIG_MAX_PT_IRQ_ENTRIES        64U
#define CONFIG_STACK_SIZE                0x2000U
#define CONFIG_LOG_BUF_SIZE              0x40000U
#define CONFIG_LOG_DESTINATION           7U
#define CONFIG_LOW_RAM_SIZE              0x00010000U
#define CONFIG_HV_RAM_START              0x00400000UL
#define CONFIG_HV_RAM_SIZE               0x0b800000UL
#define CONFIG_PLATFORM_RAM_SIZE         0x400000000UL
#define CONFIG_SOS_RAM_SIZE              0x400000000UL
#define CONFIG_UOS_RAM_SIZE              0x200000000UL
#define CONFIG_MAX_IOAPIC_NUM            1U
#define CONFIG_MAX_IOAPIC_LINES          120U
#define CONFIG_MAX_IR_ENTRIES            256
#define CONFIG_IOMMU_BUS_NUM             0x100U
#define CONFIG_MAX_PCI_DEV_NUM           96U
#define CONFIG_MAX_MSIX_TABLE_NUM        16U
#define CONFIG_MAX_KATA_VM_NUM           0U
#define CONFIG_UEFI_OS_LOADER_NAME       "\\EFI\\org.clearlinux\\bootloaderx64.efi"

/**
 * @}
 */

#endif