stages:
- scan
- build
- test
- deploy


acrn_clang_tidy_job:
  stage: scan
  script:
    - echo "start to check coding guideline violations ..."
    - pwd
    - cd hypervisor
    - make codescan
  only:
    - merge_requests


checkpatch_job:
  stage: scan
  script:
    - echo "start to check code styles and typos ..."
    - pwd
    - git rev-list `git merge-base HEAD origin/master`..HEAD | xargs -n 1 checkpatch.pl --notree --codespell -g
  only:
    - merge_requests


build_job:
  stage: build
  script:
    - echo "start to build ..."
    - pwd
    - cd hypervisor
    - make clean
    - make RELEASE=0
  dependencies:
    - acrn_clang_tidy_job
  artifacts:
    paths:
      - hypervisor/build/
    expire_in: 3 weeks
  only:
    - merge_requests
    - schedules


test_launch_cl_zephyr_job:
  stage: test
  script:
    - echo "start to test lauching clearlinux and zehpyr ..."
    - pwd
    - /opt/fusa_ci.sh launch_2_vms
  dependencies:
    - build_job
  only:
    - merge_requests
    - schedules


test_srs_job:
  stage: test
  script:
    - echo "start to test srs lauching acrn unit test ..."
    - pwd
    - cd ../acrn-hypervisor/
    - git reset --hard && git checkout master && git pull
    - cd hypervisor
    - make clean
    - make RELEASE=0
    - cd ../../acrn-srs-test-code/
    - rm -r github
    - git reset --hard && git checkout master && git pull
    - mkdir github && cd github && git clone https://github.com/projectacrn/acrn-unit-test.git
    - cp -r ../acrn-unit-test/* acrn-unit-test/
    - cd acrn-unit-test/guest/
    - /opt/acrn-ebtool/docker_run.sh clearlinux_acrn:latest "./make_all.sh"
    - cp x86/obj/* /var/lib/tftpboot/acrn_srs/acrn/
    - cd ../../../../acrn-sliced-mainline
    - /opt/fusa_ci.sh launch_acrn_unit_test
  dependencies:
    - build_job
  only:
    - merge_requests
    - schedules


test_sas_job:
  stage: test
  script:
    - echo "start to test sas build ..."
    - pwd
    - mkdir -p ./image
    - cd ../acrn-hypervisor/
    - git reset --hard && git checkout master && git pull
    - cd ../acrn-sas-test-code/
    - git reset --hard && git checkout master && git pull
    - cd host/
    - sed -i 's/acrn-hypervisor/acrn-sliced-mainline/g' Makefile
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make boot RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/boot.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make hw RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_VTD_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_vtd.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_CPU_CAPS_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_cpu_caps.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_MMU_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_mmu.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_CPU_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_cpu.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_APIC_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_apic.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_VBOOT_GROUP 
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_vboot_group.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make init RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/init.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make lib RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/lib.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make vp-base RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/vp-base.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make vp-dm RELEASE=0
    - cp ../build/acrn-unit-test/host/bin/vp-dm.32.out ../../acrn-sliced-mainline/image/
    - cp ../host/guest/x86/stitched.bzimage ../../acrn-sliced-mainline/image/
    - /opt/fusa_ci.sh sas
  dependencies:
    - build_job
  artifacts:
    paths:
      - image/
    expire_in: 3 weeks
  only:
    - merge_requests
    

test_build_job:
  stage: test
  script:
    - echo "start to test build job ..."
    - pwd
    - mkdir -p ./image
    - cd ../acrn-hypervisor/
    - git reset --hard && git checkout master && git pull
    - cd ../acrn-sas-test-code/
    - git reset --hard && git checkout master && git pull
    - cd host/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make boot RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/boot.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make hw RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_VTD_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_vtd.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_CPU_CAPS_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_cpu_caps.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_CPU_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_cpu.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_MMU_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_mmu.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_APIC_GROUP
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_apic.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make RELEASE=1 hw MODULE_GROUP_OBJ=HW_VBOOT_GROUP 
    - cp ../build/acrn-unit-test/host/bin/hw.32.out ../../acrn-sliced-mainline/image/hw_vboot_group.32.out
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make init RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/init.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make lib RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/lib.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make vp-base RELEASE=1
    - cp ../build/acrn-unit-test/host/bin/vp-base.32.out ../../acrn-sliced-mainline/image/
    - make clean
    - cd ../../acrn-sliced-mainline && git reset --hard && cd ../acrn-sas-test-code/host
    - make vp-dm RELEASE=0
    - cp ../build/acrn-unit-test/host/bin/vp-dm.32.out ../../acrn-sliced-mainline/image/
    - cp ../host/guest/x86/stitched.bzimage ../../acrn-sliced-mainline/image/
    - /opt/fusa_ci.sh sas
  dependencies:
    - build_job
  artifacts:
    paths:
      - image/
    expire_in: 3 weeks
  only:
    - schedules


deploy_sample_case_job:
  stage: deploy
  script:
    - echo "start sample case test ..."
    - pwd
    - /opt/fusa_ci.sh sample_case_test
  dependencies:
    - build_job
    - test_sas_job
  only:
    - merge_requests


deploy_build_job:
  stage: deploy
  script:
    - echo "start to deploy and run tests ..."
    - /opt/fusa_ci.sh $BUILD_TYPE
  dependencies:
    - build_job
    - test_build_job
  only:
    - schedules
