#ifndef CONFIG_DEBUG
#define CONFIG_DEBUG

#undef CONFIG_COM_BASE

#define CONFIG_SERIAL_LEGACY 1
#define CONFIG_SERIAL_PIO_BASE 0x3f8UL
#define CONFIG_COM_BASE 0x3f8U
#define CONFIG_CONSOLE_LOGLEVEL_DEFAULT 5U

#endif /* CONFIG_DEBUG */
